### ISSUE TITLE
[QUESTION] Multiple shareable CSS

### ISSUE THREAD

**Issue by motss** [aelbore/rollup-plugin-inline-lit-element#1]
Does this support inlining multiple shareable CSS component?

```css
/** common.css */
:host {
  display: block;
}

* {
  box-sizing: border-box;
}
```

```css
/** button.css */
button {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;

  background: inherit;
  color: inherit;
  font: inherit;
  border: none;
}
```

```js
/** Input */
...
import 'common.css';
import 'button.css';

...
```

```ts
/** Expected output */
...
static styles = [
  css`:host { display: block; }`,
  css`button { ... /** Truncate for brevity */ }`,
];
...
```
